version: '3.8'

services:
  gateway:
    container_name: 'gateway'
    image: 'ghcr.io/sammywhamy/scaling-separate-gateway-gateway:0.1.12'
    build: './gateway'
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BOT_REPLICAS=${BOT_REPLICAS}
      - SHARD_COUNT=${SHARD_COUNT}
      - LOG_LEVEL=${LOG_LEVEL}
    networks:
      - 'discord'
  bot_p:
    image: 'ghcr.io/sammywhamy/scaling-separate-gateway-bot:0.1.2'
    restart: on-failure
    deploy:
      replicas: ${BOT_P_REPLICAS}
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
    networks:
      - 'discord'
  bot_s:
    image: 'ghcr.io/sammywhamy/scaling-separate-gateway-bot:0.1.3'
    restart: on-failure
    deploy:
      replicas: ${BOT_S_REPLICAS}
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
    networks:
      - 'discord'

networks:
  discord:
    name: 'discord'
    external: true
