version: '3.8'

services:
  gateway:
    container_name: 'gateway'
    # image: 'ghcr.io/sammywhamy/scaling-separate-gateway-gateway:latest'
    build: './gateway'
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BOT_REPLICAS=${BOT_REPLICAS}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - SHARD_COUNT=${SHARD_COUNT}
      - LOG_LEVEL=${LOG_LEVEL}
    networks:
      - 'discord'
  bot:
    # image: 'ghcr.io/sammywhamy/scaling-separate-gateway-bot:latest'
    build: './bot'
    restart: unless-stopped
    deploy:
      replicas: ${BOT_REPLICAS}
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
    networks:
      - 'discord'

networks:
  discord:
    name: 'discord'
    external: true
